import CreateHeadingForm from "@/components/admin/HeadingForm";
import { ArrowLeft } from "lucide-react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.jpg",
  },
};

const AdminPage = () => {
  return (
    <div className="flex flex-col items-center justify-center my-16 pr-12 gap-y-4">
      <h1 className="text-xl font-bold">Welcome the CEFR TEST Dashboard</h1>
      <div className="flex items-center gap-1 cursor-pointer hover:underline text-blue-500 hover:opacity-75 ">
        <ArrowLeft
          className="h-5 w-5 text-blue-500 hover:translate-x-[-3px] transition-all"
          strokeWidth={0.75}
        />
        <p className="text-sm to-muted-foreground text-blue-500">
          Choose the Link
        </p>
      </div>
    </div>
  );
};

export default AdminPage;
